server:
  port: 8001
  servlet:
    context-path: /api/third
spring:
  # redis
  redis:
    port: 6379
    host: localhost
    database: 0
  # rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /api
    username: api
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
#腾讯短信服务
#tencent:
#  secretId: xxx
#  secretKey: xxx
#  sdkAppId: xxx
#  signName: xxx
#  templateId: xxx

#阿里云短信
aliyun:
  sms:
    accessKeyId: #你的accessKeyId
    accessKeySecret: #你的accessKeySecret
    signName: 阿里云短信测试
    templateCode: SMS_154950909



